### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by littleyoda** [lestard/structured-list#5]
I would like to use RecursiveTreeItem.java in my program, but for structured-list a licence is missing.
Can you please add one?

**Comment by lestard** [comment]
Hi, thanks for your interest. 
You can use the `RecursiveTreeItem` under the Apache license. 

I've [added license informations](https://github.com/lestard/structured-list/commit/5aa01f66925b78ac8d6d5be7d942eb5e0da823d0) to the project. The application as a whole now has a GPLv2 license. 

However the `RecursiveTreeItem` is indeed meant to be a reusable component so I've added a specific license header of the apache license to this particular file. 

I would be happy to hear what you are building with it and if it is useful for you :-)

**Comment by littleyoda** [comment]
thanks.
